CUDA_VISIBLE_DEVICES=0 python train_bio.py --data_dir ./dataset/gda \
--transformer_type bert \
--model_name_or_path allenai/scibert_scivocab_cased \
--save_path saved_model/pair_gda.pkt \
--load_path  "" \
--train_pickle train.pkl \
--dev_pickle dev.pkl \
--test_pickle test.pkl \
--train_batch_size 4 \
--test_batch_size 8 \
--gradient_accumulation_steps 4 \
--num_labels 1 \
--learning_rate 2e-5 \
--max_grad_norm 1.0 \
--warmup_ratio 0.06 \
--num_train_epochs 20.0 \
--evaluation_steps 500 \
--seed 66 \
--max_mention 35 \
--num_class 2
